"""empty message

Revision ID: 2ede1a1f3763
Revises: f58ab27b147b
Create Date: 2023-09-17 21:00:00.681232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ede1a1f3763'
down_revision = 'f58ab27b147b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
